############################################################
#
# 文件微服务
# web访问端口号  约定：8004
#
############################################################
server:
  port: 8004
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  application:
    name: service-files
  redis:
    port: 6379
    database: 0  #使用redis中第几个库
    host: 127.0.0.1
    password: peng715
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 5120000  #请求的文件大小限制为5M
      max-request-size: 5120000
  data:
    mongodb:
      uri: mongodb://root:root@10.211.55.9:27017
      database: personal_web  #数据库的名字
  cloud:
    zipkin:
      # 配置zipkin采集的服务地址，数据会发送到这里
      base-url: http://127.0.0.1:9411/
      sender:
        # 数据采集的传输通信方式，web http的形式
        type: web
    sleuth:
      sampler:
        # 数据采样比例（百分数），0~1
        probability: 0.8
########################################
# fastdfs配置
########################################
fdfs:
  connect-timeout: 30
  so-timeout: 30
  tracker-list: 10.211.55.9:22122

############################################################
#  springCloud 相关配置
# eureka client 配置信息
#
############################################################
eureka:
  #自定义eureka server的信息
  server:
    hostname: eureka
    port: 7000
  client:
    # 所有的微服务都必须注册到eureka中
    register-with-eureka: true
    # 从注册中心获得检索服务实例
    fetch-registry: true
    # 注册中心的服务地址
    service-url:
      defaultZone: http://10.211.55.9:7001/eureka/,http://10.211.55.9:7000/eureka/

# 配置hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000   # 设置hystrix超时时间，超过10秒触发降级
      circuitBreaker:   # 配置断路器
        enabled: true
        requestVolumeThreshold: 30    # 触发熔断最小请求次数，默认：20
        sleepWindowInMilliseconds: 5000    # 熔断后过几秒后尝试半开状态（请求重试），默认：5s
        errorThresholdPercentage: 50  # 触发熔断的失败率（异常率/阈值），默认：50



############################################################
#
# 项目中所用到的变量配置
#
############################################################
# 定义管理员人脸图片数据临时存储的目录
adminFace:
  temp_path: /usr/local/apache-tomcat-9.0.37/webapps/personalWeb_temp_face/

# 定义接口地址
transferInterface:
  article: http://10.211.55.9:8001/
  article_html: http://10.211.55.9:8002/
  user: http://10.211.55.9:8003/
  files: http://10.211.55.9:8004/
  admin: http://10.211.55.9:8005/