############################################################
#
# article 静态化微服务
# web访问端口号  约定：8002
#
############################################################
server:
  port: 8002
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
#  profiles:
#    active: dev   # yml中配置文件的环境配置，dev：开发环境，test：测试环境，prod：生产环境
  application:
    name: service-article-html
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://root:root@10.211.55.9:27017
      database: personal_web
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates/
  rabbitmq:
    host: 10.211.55.9
    port: 5672
    username: guest
    password: guest
    virtual-host: capture
  cloud:
    zipkin:
      # 配置zipkin采集的服务地址，数据会发送到这里
      base-url: http://127.0.0.1:9411/
      sender:
        # 数据采集的传输通信方式，web http的形式
        type: web
      sleuth:
        sampler:
          # 数据采样比例（百分数），0~1
          probability: 0.8

############################################################
#
# eureka client 配置信息
#
############################################################
eureka:
  #自定义eureka server的信息
  server:
    hostname: eureka
    port: 7000
  client:
    # 所有的微服务都必须注册到eureka中
    register-with-eureka: true
    # 从注册中心获得检索服务实例
    fetch-registry: true
    # 注册中心的服务地址
    service-url:
      defaultZone: http://eureka-cluster:7001/eureka/,http://eureka:7000/eureka/

# 配置hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000   # 设置hystrix超时时间，超过10秒触发降级
      circuitBreaker:   # 配置断路器
        enabled: true
        requestVolumeThreshold: 30    # 触发熔断最小请求次数，默认：20
        sleepWindowInMilliseconds: 5000    # 熔断后过几秒后尝试半开状态（请求重试），默认：5s
        errorThresholdPercentage: 50  # 触发熔断的失败率（异常率/阈值），默认：50





# 定义freemarker生成的html位置
freemarker:
  html:
    target: /Users/pengfeizhang/Desktop/javaProject/PerosonalWeb/freemarker_html/ #做初次使用freemarker 测试用的路径
    article: /Users/apache-tomcat-8.5.50/webapps/imooc-news/portal/a
# 定义接口地址
transferInterface:
  article: http://www.imoocnews.com:8001/
  article_html: http://www.imoocnews.com:8002/
  user: http://www.imoocnews.com:8003/
  files: http://www.imoocnews.com:8004/
  admin: http://www.imoocnews.com:8005/
# 设置域名，在java代码中获取，这里是资源配置
website:
  domain-name: imoocnews.com
