server:
  port: 8130
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可
spring:
  redis:
    port: 6379
    database: 0  #使用redis中第几个库
    host: 127.0.0.1