############################################################
#
# admin微服务
# web访问端口号  约定：8005
#
############################################################
server:
  port: 8005
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  application:
    name: service-admin
#  profiles:
#    active: dev   # yml中配置文件的环境配置，dev：开发环境，test：测试环境，prod：生产环境
  datasource:                                         # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://localhost:3306/imooc_news?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  redis:
    port: 6379
    database: 0  #使用redis中第几个库
    host: 127.0.0.1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://root:root@10.211.55.9:27017
      database: personal_web  #数据库的名字
############################################################
#
# mybatis 配置 mapper 配置
#
############################################################
mybatis:
  type-aliases-package: com.capture.pojo          # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 通用 Mapper 配置
mapper:
  mappers: com.capture.my.mapper.MyMapper
  not-empty: false    # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL
# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true

############################################################
# 以下是springCloud 相关配置
# eureka client 配置信息
#
############################################################
eureka:
  # 自定义eureka server的信息
  server:
    hostname: eureka
    port: 7000
  client:
    # 所有的微服务都必须注册到eureka中
    register-with-eureka: true
    # 从注册中心获得检索服务实例
    fetch-registry: true
    # 注册中心的服务地址
    service-url:
      defaultZone: http://eureka-cluster:7001/eureka/,http://eureka:7000/eureka/

ribbon:
  ConnectTimeout: 50000          # 创建连接的超时时间，单位：ms
  ReadTimeout: 50000             # 在连接创建好以后，调用接口的超时时间，单位：ms
  MaxAutoRetries: 1             # 最大重试次数
  MaxAutoRetriesNextServer: 2   # 切换到下个微服务实例的重试次数
  # 当请求到某个微服务5s，超时后会进行重试，先重试连接自己当前的这个实例
  # 如果当前重试失败1次，则会切换到访问集群中的下一个微服务实例，切换最大为2次

# 配置feign
feign:
#  client:
#    config:
#      # 配置服务提供方的名称
#      service-user:
#        loggerLevel: FULL
  hystrix:
    enabled: true   # 打开feign客户端的内置hystrix




############################################################
#
# 项目中所用到的变量配置
#
############################################################
website:
  domain-name: imoocnews.com
# 定义接口地址
transferInterface:
  article: http://www.imoocnews.com:8001/
  article_html: http://www.imoocnews.com:8002/
  user: http://www.imoocnews.com:8003/
  files: http://www.imoocnews.com:8004/
  admin: http://www.imoocnews.com:8005/